import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import StoreProvider from "./StoreProvider";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${poppins.style} scrollbar-hide`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
